config/routes.rb
Rails.application.routes.draw do
  constraints Clearance::Constraints::SignedIn.new do
      root to: "dashboards#show"
  end
  root to: "homes#show"
  resources :songs, only: [:create, :show] do
    member do
      post "like", to: "likes#create"
      delete "unlike", to: "likes#destroy"
    end
  end

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, only: [:create]

  resources :users, only: [:create, :show] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in", to: "sessions#new", as: "sign_in"
  delete "/sign_out", to:  "sessions#destroy", as: "sign_out"
  get "/sign_up", to: "users#new", as: "sign_up"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guest.rb
class Guest
  def email
    ""
  end

  def liked?(_)
    false
  end
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :user

  validates :song_url, presence: true, format: URI::regexp(%w(http https))
  validates :user, presence: true

  before_create :set_duration_title

  scope :white,  -> { where("duration > ? and duration < ?", 30, 90)}
  scope :green,  -> { where("duration > ? and duration < ?", 91, 180)}
  scope :black,  -> { where("duration > ? and duration < ?", 181, 300) }
  scope :herbal, -> { where("duration > ?", 301) }


  delegate :username, to: :user

  private

  def set_duration_title
    truncated_video_id = self.song_url.split('=').last
    video = Yt::Video.new id: truncated_video_id
    self.duration = video.duration
    # self.title = video.title
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  validates :username, presence: true, uniqueness: true

  has_many :songs, dependent: :destroy
  has_many :likes
  has_many :liked_songs, through: :likes, source: :song

  def like(song)
    liked_songs << song
  end

  def unlike(song)
    liked_songs.destroy(song)
  end

  def liked?(song)
    liked_song_ids.include?(song.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception

  def current_user
    super || Guest.new
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @song = Song.new
    @songs = current_user.songs
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def show
    render
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController

  private

  def authenticate(_)
    super(session_params)
  end

  def session_params
    { session: session_params_with_email }
  end

  def session_params_with_email
    params.require(:session).permit(:password).merge(email: user.email)
  end

  def user
    User.where(email: email_or_username).or(User.where(username: email_or_username)).first || Guest.new
  end

  def email_or_username
    params[:session][:email_or_username]
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def create
    song = current_user.songs.create(song_params)
    redirect_to root_path, redirect_options_for(song)
  end

  private

  def song_params
    params.require(:song).permit(:song_url, :notes, :duration, :title)
  end

  def redirect_options_for(song)
    if song.persisted?
      flash[:notice] = 'Song added successfully'
    else
      flash[:alert] = 'Good old something went wrong'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @songs = @user.songs
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/embed_video_helper.rb
module EmbedVideoHelper

  def embed(youtube_url, w, h)
    # TODO: better way to get the id, regex?
    youtube_id = youtube_url.split("=").last

    content_tag(:iframe, nil, src: "https://youtube.com/embed/#{youtube_id}", width:w, height:h)
  end

end

app/views/dashboards/show.html.haml
%h3 Add a song
%p Song URL example https://www.youtube.com/watch?v=uffJ33bcYec (this is fake)

= form_for @song do |form|
  = form.url_field :song_url, placeholder: "Song URL", required: true
  = form.text_field :notes, placeholder: "Notes"
  = form.submit "Submit"

%h2.category= 'White tea' if @songs.white.present?
= render @songs.white

%h2.category= 'Green tea' if @songs.green.present?
= render @songs.green

%h2.category= 'Black tea' if @songs.black.present?
= render @songs.black

%h2.category= 'Herbal tea' if @songs.herbal.present?
= render @songs.herbal

app/views/homes/show.html.haml
%h1 Welcome to Steeping Tea

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Steepingtea2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>STEEPING TEA</h1>
    <% if signed_in? %>
      <p> Signed in as: <%= current_user.username %>
    <%= link_to 'Sign out', sign_out_path, method: :delete %></p>
    <% else %>
      <%= link_to 'Sign in', sign_in_path %>
      <%= link_to 'Create account', sign_up_path %> 
    <% end %>

    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/songs/_song.html.haml
-# %p= link_to song.username, song.user
= embed(song.song_url, 200, 150)
-# %p= song.title
- unless song.notes.empty?
  %p= song.notes

app/views/users/_form.html.haml
%p
  = form.label :email
  = form.email_field :email
%p  
  = form.label :username
  = form.text_field :username
%p  
  = form.label :password
  = form.password_field :password

app/views/users/new.html.haml
#clearance
  %h2 Create account

  = form_for @user do |form|
    = render partial: '/users/form', object: form
    %p
      = form.submit

app/views/users/show.html.haml
%h1= @user.username

= render @songs